test_app/config/routes.rb
Rails.application.routes.draw do
  root 'blog#index'
  
  get 'blog/index'

  get 'blog/show'

  get 'blog/new'

  post 'blog/create'

  get 'blog/edit'

  get 'blog/update'

  get 'blog/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

test_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

test_app/app/models/post.rb
class Post < ApplicationRecord
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

test_app/app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to blog_index_path
  end

  def edit
  end

  def update
  end

  def destroy
  end


private
def post_params
  params.require(:@post).permit(:name, :title, :content)
end

end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/helpers/blog_helper.rb
module BlogHelper
end

test_app/app/views/blog/destroy.html.erb
<h1>Blog#destroy</h1>
<p>Find me in app/views/blog/destroy.html.erb</p>

test_app/app/views/blog/edit.html.erb
<h1>Blog#edit</h1>
<p>Find me in app/views/blog/edit.html.erb</p>

test_app/app/views/blog/index.html.erb
<h1>Blog#index</h1>
<p>Find me in app/views/blog/index.html.erb</p>

<head>
  <style>
       @import url(http://fonts.googleapis.com/earlyaccess/nanumpenscript.css);)
  </style>
</head>

<body>
  <img src = "Assets/st.jpeg" width="500" height="400"/>
  <div class= "2018-06-01">
    <h1>STEROID 10기&11기 PERPORMANCE</h1>
    <P>성균관대학교 글경이 유일하게 허락한 마약! STEORIOD에서 정기공연을 합니다 </P>
    <P>When : 2018/06/01/7pm</P>
    <p>Where : 대학로 에픽 153</p>
    <a href="https://map.naver.com/local/siteview.nhn?code=35209147">그래서 어디서 하냐국우우우</a>
</body>



<%=link_to '아무거나 얘기하기 찹!찹!찹!', blog_new_path%><br><br>
<table> 
  <tr>
      <th>name</th>
      <th>title</th>
      <th>content</th>
  </tr>
  <% @posts.each do |p| %>
  <tr>
      <td><%= p.name%></td>
      <td><%= p.title%></td>
      <td><%= p.content%></td>
  </tr>
  <%end%>
</table>

test_app/app/views/blog/new.html.erb
<h1>Blog#new</h1>
<p>Find me in app/views/blog/new.html.erb</p>
<%= form_for :@post, url: blog_create_path do |f| %>
 아아아 너는 누구십니까? : <%= f.text_field :name %><br>
 아아아 말씀의 주제는 뭐죠? : <%= f.text_field :title %><br>
 아아아 당신의 애기를 해줘요~ : <%= f.text_area :content %> <br>
        <%= f.submit %>
<% end %>

test_app/app/views/blog/show.html.erb
<h1>Blog#show</h1>
<p>Find me in app/views/blog/show.html.erb</p>

test_app/app/views/blog/update.html.erb
<h1>Blog#update</h1>
<p>Find me in app/views/blog/update.html.erb</p>

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>!WELCOME TO STEROID!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>